### ISSUE TITLE
sncli create - error

### ISSUE THREAD

**Issue by arttobe** [insanum/sncli#61]
When i try to create a note i get this error 

Traceback (most recent call last):
  File "/home/moritz/.local/bin/sncli", line 11, in <module>
    sys.exit(main())
  File "/home/moritz/.local/lib/python3.6/site-packages/simplenote_cli/sncli.py", line 1379, in main
    sn.cli_note_create(False, title)
  File "/home/moritz/.local/lib/python3.6/site-packages/simplenote_cli/sncli.py", line 1113, in cli_note_create
    content = self.exec_cmd_on_note(None)
  File "/home/moritz/.local/lib/python3.6/site-packages/simplenote_cli/sncli.py", line 99, in exec_cmd_on_note
    focus_position = self.gui_body_get().focus_position
  File "/home/moritz/.local/lib/python3.6/site-packages/simplenote_cli/sncli.py", line 227, in gui_body_get
    return self.master_frame.contents['body'][0]
AttributeError: 'sncli' object has no attribute 'master_frame'

**Comment by arttobe** [comment]
Thank you for your answer
python3 --version
Python 3.6.6

i installed over pip3 install sncli
my system runs on fedora 28

**Comment by swalladge** [comment]
@arttobe thanks. I believe I can reproduce the error. Working on a fix.

**Comment by swalladge** [comment]
@arttobe I should be fixed now. Please install the latest git version:

```
pip install -U git+https://github.com/insanum/sncli.git
```

And let us know if you see any other crashes. :)
